# Generated by Django 5.1.2 on 2024-10-26 12:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Certificate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "certificate_type",
                    models.CharField(
                        choices=[
                            ("GCP", "Good Clinical Practice Certificate"),
                            ("QRC", "Qualitative Record Certificate"),
                            ("CTC", "Consent Training Certificate"),
                            ("Other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "other_certificate_name",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("issue_date", models.DateField()),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("file", models.FileField(upload_to="certificates/")),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "institution",
                    models.CharField(
                        default="King Hussein Cancer Center", max_length=255
                    ),
                ),
                ("mobile", models.CharField(max_length=20)),
                (
                    "khcc_employee_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("KHCC investigator", "KHCC investigator"),
                            ("Non-KHCC investigator", "Non-KHCC investigator"),
                            (
                                "Research Assistant/Coordinator",
                                "Research Assistant/Coordinator",
                            ),
                            ("OSAR head", "OSAR head"),
                            ("OSAR coordinator", "OSAR coordinator"),
                            ("IRB chair", "IRB chair"),
                            ("RC coordinator", "RC coordinator"),
                            ("IRB member", "IRB member"),
                            ("RC chair", "RC chair"),
                            ("RC member", "RC member"),
                            ("RC coordinator", "RC coordinator"),
                            ("AHARPP Head", "AHARPP Head"),
                            ("System administrator", "System administrator"),
                            ("CEO", "CEO"),
                            ("CMO", "CMO"),
                            ("AIDI Head", "AIDI Head"),
                            ("Grant Management Officer", "Grant Management Officer"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="photos/"),
                ),
                ("is_approved", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
