# Generated by Django 5.1.2 on 2024-11-05 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_role"),
    ]

    operations = [
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name="document",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("GCP", "Good Clinical Practice Certificate"),
                    ("QRC", "Qualitative Record Certificate"),
                    ("CTC", "Consent Training Certificate"),
                    ("CV", "Curriculum Vitae"),
                    ("Other", "Other"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="groups",
            field=models.ManyToManyField(
                blank=True, related_name="user_profiles", to="users.group"
            ),
        ),
    ]
