# Generated by Django 5.1.2 on 2024-10-28 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_userprofile_cv_document_delete_certificate"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="full_name",
            field=models.CharField(
                default="",
                help_text="Full name (at least three names required)",
                max_length=255,
            ),
        ),
    ]
