# Generated by Django 5.1.2 on 2024-11-05 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_group_alter_document_document_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="full_name",
            field=models.CharField(
                default="",
                help_text="Full name (at least two names required)",
                max_length=255,
            ),
        ),
    ]
