# Generated by Django 5.1.2 on 2024-10-29 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_userprofile_full_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="cv",
        ),
    ]
