# Generated by Django 5.1.2 on 2024-11-05 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_userprofile_full_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="full_name",
            field=models.CharField(
                default="",
                help_text="Full name (at least tw names required)",
                max_length=255,
            ),
        ),
    ]
