# Generated by Django 5.1.2 on 2024-11-08 22:53

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import users.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_userprofile_full_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="document",
            options={"ordering": ["-uploaded_at"]},
        ),
        migrations.AlterModelOptions(
            name="group",
            options={"ordering": ["name"]},
        ),
        migrations.AlterModelOptions(
            name="role",
            options={
                "ordering": ["name"],
                "verbose_name": "Role",
                "verbose_name_plural": "Roles",
            },
        ),
        migrations.AlterModelOptions(
            name="userprofile",
            options={"ordering": ["user__username"]},
        ),
        migrations.AddField(
            model_name="group",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="group",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="group",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="systemsettings",
            name="system_email",
            field=models.EmailField(
                default="aidi@khcc.jo",
                help_text="System email address for automated messages",
                max_length=254,
            ),
        ),
        migrations.AlterField(
            model_name="systemsettings",
            name="system_user",
            field=models.ForeignKey(
                blank=True,
                help_text="System user account for automated actions",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="system_settings",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="full_name",
            field=models.CharField(
                default="",
                help_text="Full name (at least two names required)",
                max_length=255,
                validators=[users.models.validate_full_name],
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="khcc_employee_number",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Employee number can only contain letters and numbers.",
                        regex="^[A-Za-z0-9]+$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="mobile",
            field=models.CharField(
                max_length=20,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.",
                        regex="^\\+?1?\\d{9,15}$",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[
                    ("KHCC investigator", "KHCC investigator"),
                    ("Non-KHCC investigator", "Non-KHCC investigator"),
                    (
                        "Research Assistant/Coordinator",
                        "Research Assistant/Coordinator",
                    ),
                    ("OSAR head", "OSAR head"),
                    ("OSAR", "OSAR"),
                    ("IRB chair", "IRB chair"),
                    ("RC coordinator", "RC coordinator"),
                    ("IRB member", "IRB member"),
                    ("RC chair", "RC chair"),
                    ("RC member", "RC member"),
                    ("AHARPP Head", "AHARPP Head"),
                    ("System administrator", "System administrator"),
                    ("CEO", "CEO"),
                    ("CMO", "CMO"),
                    ("AIDI Head", "AIDI Head"),
                    ("Grant Management Officer", "Grant Management Officer"),
                ],
                db_index=True,
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="userprofile",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="document",
            index=models.Index(
                fields=["document_type", "expiry_date"],
                name="users_docum_documen_150d1c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="userprofile",
            index=models.Index(
                fields=["is_approved"], name="users_userp_is_appr_d8bf45_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userprofile",
            index=models.Index(fields=["role"], name="users_userp_role_c31a7e_idx"),
        ),
    ]
