# Generated by Django 5.1.2 on 2024-11-08 23:16

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_alter_userprofile_mobile_alter_userprofile_role_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="mobile",
            field=models.CharField(
                blank=True,
                default="",
                max_length=20,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.",
                        regex="^\\+?1?\\d{9,15}$",
                    )
                ],
            ),
        ),
    ]
