# Generated by Django 5.1.2 on 2024-11-04 22:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submission", "0002_researchassistant_date_added_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="coinvestigator",
            name="order",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="coinvestigator",
            name="submission",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="submission.submission"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="coinvestigator",
            unique_together={("submission", "user")},
        ),
    ]
