# Generated by Django 5.1.2 on 2024-10-29 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("submission", "0003_dynamicform_dynamicfield"),
    ]

    operations = [
        migrations.DeleteModel(
            name="DynamicField",
        ),
        migrations.DeleteModel(
            name="DynamicForm",
        ),
    ]
