# Generated by Django 5.1.2 on 2024-11-04 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submission", "0003_alter_coinvestigator_order_and_more"),
        ("users", "0002_role"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="coinvestigator",
            name="role_in_study",
        ),
        migrations.AddField(
            model_name="coinvestigator",
            name="roles",
            field=models.ManyToManyField(
                related_name="coinvestigators", to="users.role"
            ),
        ),
    ]
