# Generated by Django 5.1.2 on 2024-10-29 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submission", "0004_delete_dynamicfield_delete_dynamicform"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="is_locked",
            field=models.BooleanField(default=False),
        ),
    ]
