# Generated by Django 5.1.2 on 2024-11-08 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submission", "0005_statuschoice_alter_submission_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coinvestigator",
            name="submission",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="coinvestigators",
                to="submission.submission",
            ),
        ),
        migrations.AlterField(
            model_name="researchassistant",
            name="submission",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="research_assistants",
                to="submission.submission",
            ),
        ),
    ]
