# Generated by Django 5.1.2 on 2024-11-08 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submission", "0006_alter_coinvestigator_submission_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submission",
            name="irb_number",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
