# Generated by Django 5.1.2 on 2024-10-31 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("submission", "0007_submission_locked_at_submission_locked_by"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="submission",
            name="locked_at",
        ),
        migrations.RemoveField(
            model_name="submission",
            name="locked_by",
        ),
    ]
