# Generated by Django 5.1.2 on 2024-10-31 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submission", "0008_remove_submission_locked_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "system_email",
                    models.EmailField(
                        default="aidi@khcc.jo",
                        help_text="System email address used for automated messages",
                        max_length=254,
                    ),
                ),
            ],
            options={
                "verbose_name": "System Settings",
                "verbose_name_plural": "System Settings",
            },
        ),
    ]
