# Generated by Django 5.1.2 on 2024-11-10 02:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms_builder", "0003_merge_20241108_1706"),
        ("submission", "0009_alter_versionhistory_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InvestigatorFormSubmission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_submitted", models.DateTimeField(auto_now_add=True)),
                ("version", models.PositiveIntegerField()),
                (
                    "form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="forms_builder.dynamicform",
                    ),
                ),
                (
                    "investigator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "submission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="investigator_form_submissions",
                        to="submission.submission",
                    ),
                ),
            ],
            options={
                "ordering": ["date_submitted"],
                "unique_together": {("submission", "form", "investigator", "version")},
            },
        ),
    ]
