# Generated by Django 5.1.2 on 2024-10-31 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submission", "0009_systemsettings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formdataentry",
            name="field_name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="formdataentry",
            name="submission",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="submission.submission"
            ),
        ),
        migrations.AlterField(
            model_name="formdataentry",
            name="value",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="formdataentry",
            name="version",
            field=models.IntegerField(default=1),
        ),
    ]
