# Generated by Django 5.1.2 on 2024-10-31 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submission", "0010_alter_formdataentry_field_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formdataentry",
            name="field_name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="formdataentry",
            name="submission",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="form_data_entries",
                to="submission.submission",
            ),
        ),
        migrations.AlterField(
            model_name="formdataentry",
            name="value",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="formdataentry",
            name="version",
            field=models.PositiveIntegerField(default=1),
        ),
    ]
