# Generated by Django 5.1.2 on 2024-11-13 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submission", "0010_investigatorformsubmission"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="archived_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="submission",
            name="is_archived",
            field=models.BooleanField(default=False),
        ),
    ]
