# Generated by Django 5.1.2 on 2024-11-13 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submission", "0011_submission_archived_at_submission_is_archived"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="coinvestigator",
            name="roles",
        ),
        migrations.AddField(
            model_name="coinvestigator",
            name="roles",
            field=models.JSONField(default=list),
        ),
    ]
