# Generated by Django 5.1.2 on 2024-11-29 19:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submission", "0012_remove_coinvestigator_roles_coinvestigator_roles"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="irb_toggle_date",
            field=models.DateTimeField(
                blank=True,
                help_text="When was this submission toggled for IRB review",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="submission",
            name="irb_toggled_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="irb_toggled_submissions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="submission",
            name="rc_toggle_date",
            field=models.DateTimeField(
                blank=True,
                help_text="When was this submission toggled for RC review",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="submission",
            name="rc_toggled_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="rc_toggled_submissions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="submission",
            name="show_in_irb",
            field=models.BooleanField(
                default=False, help_text="Show this submission in the IRB dashboard"
            ),
        ),
        migrations.AddField(
            model_name="submission",
            name="show_in_rc",
            field=models.BooleanField(
                default=False, help_text="Show this submission in the RC dashboard"
            ),
        ),
        migrations.AlterField(
            model_name="submission",
            name="study_type",
            field=models.CharField(default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
