# Generated by Django 5.1.3 on 2024-11-30 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submission", "0013_permissionchangelog"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="show_in_irb",
            field=models.BooleanField(
                default=False, help_text="Toggle visibility for IRB members"
            ),
        ),
        migrations.AddField(
            model_name="submission",
            name="show_in_rc",
            field=models.BooleanField(
                default=False, help_text="Toggle visibility for RC members"
            ),
        ),
    ]
