# Generated by Django 5.1.3 on 2024-11-30 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("submission", "0014_submission_show_in_irb_submission_show_in_rc"),
    ]

    operations = [
        migrations.RenameField(
            model_name="submission",
            old_name="irb_number",
            new_name="khcc_number",
        ),
    ]
