# Generated by Django 5.1.2 on 2024-11-29 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submission", "0014_remove_submission_irb_toggle_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="show_in_irb",
            field=models.BooleanField(
                default=False, help_text="Toggle visibility for IRB members"
            ),
        ),
        migrations.AddField(
            model_name="submission",
            name="show_in_rc",
            field=models.BooleanField(
                default=False, help_text="Toggle visibility for RC members"
            ),
        ),
    ]
