# Generated by Django 5.1.3 on 2024-11-30 19:40

import iRN.constants
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submission", "0015_rename_irb_number_submission_khcc_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="submission",
            name="status",
            field=models.CharField(
                choices=iRN.constants.get_submission_status_choices,
                default="draft",
                max_length=50,
            ),
        ),
    ]
