# Generated by Django 5.1.3 on 2024-12-01 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submission", "0017_studyaction_studyactiondocument"),
    ]

    operations = [
        migrations.AddField(
            model_name="studyaction",
            name="version",
            field=models.IntegerField(default=1),
        ),
    ]
