# Generated by Django 5.1.3 on 2024-12-01 21:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submission", "0021_remove_submission_submitted_by_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="submitted_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who submitted the submission",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="submitted_submissions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
