# Generated by Django 5.1.3 on 2024-12-04 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submission", "0023_versionhistory_submitted_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="submission",
            name="forms_complete",
            field=models.BooleanField(default=False),
        ),
    ]
