# Generated by Django 5.1.3 on 2024-12-04 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("submission", "0024_submission_forms_complete"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="submission",
            name="forms_complete",
        ),
    ]
