# Generated by Django 5.1.3 on 2024-12-04 21:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("submission", "0025_remove_submission_forms_complete"),
    ]

    operations = [
        migrations.AddField(
            model_name="formdataentry",
            name="study_action",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="form_data_entries",
                to="submission.studyaction",
            ),
        ),
    ]
