# Generated by Django 5.1.2 on 2024-11-05 14:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "forms_builder",
            "0002_alter_dynamicform_options_alter_formfield_options_and_more",
        ),
        ("review", "0001_initial"),
        ("submission", "0004_remove_coinvestigator_role_in_study_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="reviewrequest",
            old_name="date_requested",
            new_name="created_at",
        ),
        migrations.AddField(
            model_name="review",
            name="submission_version",
            field=models.PositiveIntegerField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="reviewrequest",
            name="submission_version",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="reviewrequest",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="formresponse",
            name="review",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="review.review"
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="comments",
            field=models.TextField(default="None"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="review",
            name="review_request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="review.reviewrequest"
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="reviewer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="submission",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="submission.submission"
            ),
        ),
        migrations.AlterField(
            model_name="reviewrequest",
            name="conflict_of_interest_details",
            field=models.TextField(blank=True, default=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="reviewrequest",
            name="message",
            field=models.TextField(blank=True, default="None"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="reviewrequest",
            name="requested_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="review_requests_created",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="reviewrequest",
            name="requested_to",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="review_requests_received",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="reviewrequest",
            name="selected_forms",
            field=models.ManyToManyField(to="forms_builder.dynamicform"),
        ),
        migrations.AlterField(
            model_name="reviewrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("accepted", "Accepted"),
                    ("declined", "Declined"),
                    ("completed", "Completed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="reviewrequest",
            name="submission",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="submission.submission"
            ),
        ),
    ]
