# Generated by Django 5.1.2 on 2024-11-05 20:45

import submission.models
from django.db import migrations, models

# Define the review status choices directly in the migration
REVIEW_STATUS_CHOICES = [
    ('pending', 'Pending'),
    ('declined', 'Declined'),
    ('completed', 'Completed'),
    ('overdue', 'Overdue'),
    ('extended', 'Extended'),
    ('request_withdrawn', 'Request Withdrawn'),
]

class Migration(migrations.Migration):

    dependencies = [
        ("review", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StatusChoice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.CharField(max_length=50, unique=True)),
                ("label", models.CharField(max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Status Choice",
                "verbose_name_plural": "Status Choices",
                "ordering": ["order"],
            },
        ),
        migrations.AlterField(
            model_name="reviewrequest",
            name="status",
            field=models.CharField(
                choices=REVIEW_STATUS_CHOICES,
                max_length=50,
                default='pending'
            ),
        ),
    ]
