# Generated by Django 5.1.2 on 2024-11-05 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("review", "0002_rename_date_requested_reviewrequest_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reviewrequest",
            name="submission_version",
            field=models.PositiveIntegerField(
                help_text="Version number of the submission being reviewed"
            ),
        ),
    ]
