# Generated by Django 5.1.2 on 2024-11-05 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("review", "0002_statuschoice_alter_reviewrequest_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="is_archived",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="reviewrequest",
            name="extension_reason",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="reviewrequest",
            name="extension_requested",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="reviewrequest",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="reviewrequest",
            name="order",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="reviewrequest",
            name="proposed_deadline",
            field=models.DateField(blank=True, null=True),
        ),
    ]
