# Generated by Django 5.1.2 on 2024-11-05 22:46

import review.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("review", "0003_review_is_archived_reviewrequest_extension_reason_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reviewrequest",
            name="status",
            field=models.CharField(
                choices=review.models.get_status_choices,
                default="pending",
                max_length=50,
            ),
        ),
    ]
