# Generated by Django 5.1.2 on 2024-11-05 23:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("review", "0004_alter_reviewrequest_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="reviewrequest",
            name="can_forward",
            field=models.BooleanField(
                default=False, help_text="Whether this reviewer can forward to others"
            ),
        ),
        migrations.AddField(
            model_name="reviewrequest",
            name="forwarding_chain",
            field=models.JSONField(
                default=list, help_text="List of users who forwarded this request"
            ),
        ),
        migrations.AddField(
            model_name="reviewrequest",
            name="parent_request",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="child_requests",
                to="review.reviewrequest",
            ),
        ),
        migrations.AlterField(
            model_name="review",
            name="comments",
            field=models.TextField(blank=True),
        ),
    ]
