# Generated by Django 5.1.2 on 2024-11-08 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("review", "0009_alter_review_options_review_is_completed"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="review",
            options={},
        ),
        migrations.RemoveField(
            model_name="review",
            name="is_completed",
        ),
    ]
