# Generated by Django 5.1.2 on 2024-11-09 20:49

import iRN.constants
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("review", "0011_alter_reviewrequest_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reviewrequest",
            name="status",
            field=models.CharField(
                choices=iRN.constants.get_status_choices,
                default="pending",
                max_length=50,
            ),
        ),
    ]
