# Generated by Django 5.1.2 on 2024-11-29 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("review", "0012_alter_reviewrequest_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="review",
            options={
                "permissions": [
                    ("view_any_review", "Can view any review regardless of assignment"),
                    ("change_submission_status", "Can change submission status"),
                ]
            },
        ),
    ]
