# Generated by Django 5.1.3 on 2024-11-30 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("review", "0014_notepadentry"),
    ]

    operations = [
        migrations.DeleteModel(
            name="NotepadEntry",
        ),
    ]
