# Generated by Django 5.1.2 on 2024-10-26 23:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="respond_by",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(
                    2024, 11, 9, 23, 53, 24, 143515, tzinfo=datetime.timezone.utc
                ),
                null=True,
            ),
        ),
    ]
