# Generated by Django 5.1.2 on 2024-10-27 00:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0003_alter_message_attachments_alter_message_respond_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="respond_by",
            field=models.DateTimeField(
                blank=True,
                default=datetime.datetime(
                    2024, 11, 10, 0, 47, 24, 961306, tzinfo=datetime.timezone.utc
                ),
                null=True,
            ),
        ),
    ]
