# Generated by Django 5.1.2 on 2024-11-08 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0003_messageattachment_content_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="messageattachment",
            name="content_type",
        ),
    ]
