# Generated by Django 5.1.2 on 2024-11-09 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0002_alter_message_id"),
        ("messaging", "0004_remove_messageattachment_content_type"),
    ]

    operations = []
