# Generated by Django 5.1.2 on 2024-11-09 07:07

import messaging.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0005_merge_20241109_0952"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="hashtags",
        ),
        migrations.AlterField(
            model_name="message",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="messageattachment",
            name="file",
            field=models.FileField(
                upload_to="message_attachments/",
                validators=[messaging.validators.validate_file_size],
            ),
        ),
    ]
