# Generated by Django 5.1.2 on 2024-11-09 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0006_remove_message_hashtags_alter_message_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="hashtags",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="messageattachment",
            name="file",
            field=models.FileField(upload_to="message_attachments/"),
        ),
    ]
