# Generated by Django 5.1.2 on 2024-10-31 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0007_messageattachment"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="attachments",
        ),
        migrations.AddField(
            model_name="message",
            name="is_read",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="message",
            name="respond_by",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="message",
            name="thread_id",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
