# Generated by Django 5.1.3 on 2024-11-17 01:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0002_add_study_name"),
        ("messaging", "0009_remove_message_study_name_and_more"),
    ]

    operations = []
