# Generated by Django 5.1.2 on 2024-10-31 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0009_remove_message_is_read_message_attachments_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="message",
            name="attachments",
            field=models.FileField(
                blank=True, null=True, upload_to="message_attachments/"
            ),
        ),
    ]
