# Generated by Django 5.1.3 on 2024-11-17 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0010_merge_20241117_0441"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="message",
            name="study_name",
        ),
    ]
