# Generated by Django 5.1.2 on 2024-11-03 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0011_remove_message_attachments_messageattachment"),
        ("submission", "0011_alter_formdataentry_field_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="related_submission",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="related_messages",
                to="submission.submission",
            ),
        ),
    ]
