# Generated by Django 5.1.3 on 2024-12-04 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0011_remove_message_study_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='message_type',
            field=models.CharField(choices=[('decision', 'Decision'), ('notification', 'Notification'), ('general', 'General')], default='general', max_length=20),
        ),
    ]
