# Generated by Django 5.1.2 on 2024-10-28 01:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DynamicForm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("version", models.CharField(max_length=50)),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                ("requested_per_investigator", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="StudyType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="FormField",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("number", "Number"),
                            ("date", "Date"),
                            ("choice", "Multiple Choice"),
                            ("dropdown", "Dropdown List"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "default_value",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("max_length", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "choices",
                    models.TextField(
                        blank=True,
                        help_text="Comma-separated values for choices.",
                        null=True,
                    ),
                ),
                (
                    "form",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fields",
                        to="forms_builder.dynamicform",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="dynamicform",
            name="study_types",
            field=models.ManyToManyField(
                related_name="forms", to="forms_builder.studytype"
            ),
        ),
    ]
