# Generated by Django 5.1.2 on 2024-11-04 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms_builder", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dynamicform",
            options={
                "ordering": ["order"],
                "verbose_name": "Dynamic Form",
                "verbose_name_plural": "Dynamic Forms",
            },
        ),
        migrations.AlterModelOptions(
            name="formfield",
            options={
                "verbose_name": "Form Field",
                "verbose_name_plural": "Form Fields",
            },
        ),
        migrations.AlterModelOptions(
            name="studytype",
            options={
                "verbose_name": "Study Type",
                "verbose_name_plural": "Study Types",
            },
        ),
        migrations.AddField(
            model_name="dynamicform",
            name="json_input",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="dynamicform",
            name="order",
            field=models.PositiveIntegerField(
                default=0, help_text="Defines the sequence in which forms appear"
            ),
        ),
        migrations.AddField(
            model_name="formfield",
            name="displayed_name",
            field=models.CharField(
                default="", help_text="Human-readable field name", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="formfield",
            name="help_text",
            field=models.TextField(
                blank=True,
                help_text="Explanatory text to be shown with the field.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="formfield",
            name="required",
            field=models.BooleanField(
                default=False, help_text="Is this field mandatory?"
            ),
        ),
        migrations.AddField(
            model_name="formfield",
            name="rows",
            field=models.PositiveIntegerField(
                default=3, help_text="Number of rows for textarea fields"
            ),
        ),
        migrations.AlterField(
            model_name="formfield",
            name="field_type",
            field=models.CharField(
                choices=[
                    ("text", "Text"),
                    ("email", "Email"),
                    ("tel", "Telephone"),
                    ("number", "Number"),
                    ("date", "Date"),
                    ("textarea", "Text Area"),
                    ("checkbox", "Checkboxes"),
                    ("radio", "Radio Buttons"),
                    ("select", "Dropdown List"),
                    ("choice", "Multiple Choice"),
                    ("table", "Table"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="formfield",
            name="name",
            field=models.CharField(
                help_text="Database field name (lowercase with underscores)",
                max_length=255,
            ),
        ),
    ]
