# Generated by Django 5.1.2 on 2024-11-08 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forms_builder", "0002_ensure_evaluation_type"),
        ("forms_builder", "XXXX_ensure_evaluation_type"),
    ]

    operations = []
