# Generated by Django 5.1.2 on 2024-11-29 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forms_builder", "0003_merge_20241108_1706"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="studytype",
            options={},
        ),
        migrations.RemoveField(
            model_name="studytype",
            name="requires_aharpp",
        ),
        migrations.RemoveField(
            model_name="studytype",
            name="requires_irb",
        ),
        migrations.RemoveField(
            model_name="studytype",
            name="requires_research_council",
        ),
    ]
