# Generated by Django 5.1.2 on 2024-11-06 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms_builder", "0003_alter_dynamicform_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="studytype",
            name="requires_aharpp",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="studytype",
            name="requires_grant_management",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="studytype",
            name="requires_irb",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="studytype",
            name="requires_research_council",
            field=models.BooleanField(default=False),
        ),
    ]
