# Generated by Django 5.1.2 on 2024-10-28 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("forms_builder", "0003_dynamicform_json_input"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="dynamicform",
            name="json_input",
        ),
    ]
