# Generated by Django 5.1.2 on 2024-10-29 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms_builder", "0004_remove_dynamicform_json_input"),
    ]

    operations = [
        migrations.AddField(
            model_name="formfield",
            name="help_text",
            field=models.TextField(
                blank=True,
                help_text="Explanatory text to be shown with the field.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="formfield",
            name="required",
            field=models.BooleanField(
                default=False, help_text="Is this field mandatory?"
            ),
        ),
    ]
