# Generated by Django 5.1.2 on 2024-11-06 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms_builder", "0004_studytype_requires_aharpp_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studytype",
            name="requires_grant_management",
        ),
        migrations.AddField(
            model_name="studytype",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="studytype",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="studytype",
            name="requires_aharpp",
            field=models.BooleanField(default=True, help_text="Requires AHRRP review"),
        ),
        migrations.AlterField(
            model_name="studytype",
            name="requires_irb",
            field=models.BooleanField(default=True, help_text="Requires IRB review"),
        ),
        migrations.AlterField(
            model_name="studytype",
            name="requires_research_council",
            field=models.BooleanField(default=True, help_text="Requires CR review"),
        ),
    ]
