# Generated by Django 5.1.2 on 2024-10-29 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms_builder", "0005_formfield_help_text_formfield_required"),
    ]

    operations = [
        migrations.AlterField(
            model_name="formfield",
            name="field_type",
            field=models.CharField(
                choices=[
                    ("text", "Text"),
                    ("email", "Email"),
                    ("tel", "Telephone"),
                    ("number", "Number"),
                    ("date", "Date"),
                    ("textarea", "Text Area"),
                    ("checkbox", "Checkboxes"),
                    ("radio", "Radio Buttons"),
                    ("select", "Dropdown List"),
                    ("choice", "Multiple Choice"),
                    ("table", "Table"),
                ],
                max_length=20,
            ),
        ),
    ]
