# Generated by Django 5.1.2 on 2024-10-29 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms_builder", "0006_alter_formfield_field_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="formfield",
            name="displayed_name",
            field=models.CharField(
                default="", help_text="Human-readable field name", max_length=255
            ),
        ),
        migrations.AddField(
            model_name="formfield",
            name="rows",
            field=models.PositiveIntegerField(
                default=3, help_text="Number of rows for textarea fields"
            ),
        ),
        migrations.AlterField(
            model_name="formfield",
            name="name",
            field=models.CharField(
                help_text="Database field name (lowercase with underscores)",
                max_length=255,
            ),
        ),
    ]
