# Generated by Django 5.1.2 on 2024-10-29 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms_builder", "0007_formfield_displayed_name_formfield_rows_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="dynamicform",
            name="json_input",
            field=models.TextField(blank=True, null=True),
        ),
    ]
