# Generated by Django 5.1.2 on 2024-10-29 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forms_builder", "0008_dynamicform_json_input"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="dynamicform",
            options={
                "ordering": ["order"],
                "verbose_name": "Dynamic Form",
                "verbose_name_plural": "Dynamic Forms",
            },
        ),
        migrations.AddField(
            model_name="dynamicform",
            name="order",
            field=models.PositiveIntegerField(
                default=0, help_text="Defines the sequence in which forms appear"
            ),
        ),
    ]
